//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bkgd_H
#define METASPRITE_bkgd_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>
#include <gb/cgb.h>
#include <gb/gb.h>

#define bkgd_TILE_ORIGIN 0
#define bkgd_TILE_W 8
#define bkgd_TILE_H 8
#define bkgd_WIDTH 256
#define bkgd_HEIGHT 144
#define bkgd_TILE_COUNT 6
#define bkgd_PALETTE_COUNT 1
#define bkgd_COLORS_PER_PALETTE 4
#define bkgd_TOTAL_COLORS 4
#define bkgd_MAP_ATTRIBUTES 0
extern const unsigned char bkgd_map[576];
#define bkgd_map_attributes bkgd_map

BANKREF_EXTERN(bkgd)

extern const uint8_t bkgd_tiles[48];
void scrollBkg(void);
void bkgInterrupts(void);

#endif
